import { useState, useMemo } from 'react';
import PageHeader from '../components/ui/PageHeader.jsx';
import SubNav from '../components/ui/SubNav.jsx';
import PublicationCard from '../components/publications/PublicationCard.jsx';
import EmptyState from '../components/ui/EmptyState.jsx';
import { usePublications } from '../hooks/usePublications.js';

export default function Publications() {
  const { publications } = usePublications();
  const [query, setQuery] = useState('');
  const [areaFilter, setAreaFilter] = useState('');
  const [typeFilter, setTypeFilter] = useState('');
  const [oaFilter, setOaFilter] = useState('');

  const stats = useMemo(() => {
    const total = publications.length;
    const oa = publications.filter(p => p.open === true || p.open === 'true').length;
    const years = [...new Set(publications.map(p => p.year).filter(Boolean))].sort();
    return { total, oa, subscription: total - oa, latestYear: years[years.length - 1] || '—' };
  }, [publications]);

  const filtered = useMemo(() => {
    const q = query.toLowerCase();
    return publications.filter(p => {
      const mQ = !q || p.title.toLowerCase().includes(q) || (p.authors || '').toLowerCase().includes(q) || (p.journal || '').toLowerCase().includes(q);
      const mA = !areaFilter || (p.area || '').toLowerCase().includes(areaFilter);
      const mT = !typeFilter || (p.type || '') === typeFilter;
      const mO = !oaFilter || String(p.open) === oaFilter;
      return mQ && mA && mT && mO;
    });
  }, [publications, query, areaFilter, typeFilter, oaFilter]);

  return (
    <>
      <PageHeader
        eyebrow="Research Tracks"
        title="Research"
        titleEm="Publications"
        desc="Peer-reviewed publications generated by AREF Fellows and their student cohorts across genomics, bioinformatics, and computational biology."
      />

      <SubNav />

      <div className="stats-strip">
        <div className="stats-strip-inner">
          <div className="strip-stat"><div className="strip-num">{stats.total}</div><div className="strip-label">Total Publications</div></div>
          <div className="strip-stat"><div className="strip-num">{stats.oa}</div><div className="strip-label">Open Access</div></div>
          <div className="strip-stat"><div className="strip-num">{stats.subscription}</div><div className="strip-label">Subscription</div></div>
          <div className="strip-stat"><div className="strip-num">{stats.latestYear}</div><div className="strip-label">Most Recent Year</div></div>
        </div>
      </div>

      <div className="controls">
        <input
          type="text"
          className="search-input"
          placeholder="Search by title, authors, or journal…"
          value={query}
          onChange={e => setQuery(e.target.value)}
        />
        <select className="filter-select" value={areaFilter} onChange={e => setAreaFilter(e.target.value)}>
          <option value="">All Research Areas</option>
          <option value="pathogen genomics">Pathogen Genomics</option>
          <option value="cancer genomics">Cancer Genomics</option>
          <option value="microbiome">Microbiome Research</option>
          <option value="computational biology">Computational Biology</option>
          <option value="bioinformatics">Bioinformatics</option>
        </select>
        <select className="filter-select" value={typeFilter} onChange={e => setTypeFilter(e.target.value)}>
          <option value="">All Types</option>
          <option value="Original Article">Original Article</option>
          <option value="Review">Review</option>
          <option value="Short Communication">Short Communication</option>
          <option value="Conference Paper">Conference Paper</option>
        </select>
        <select className="filter-select" value={oaFilter} onChange={e => setOaFilter(e.target.value)}>
          <option value="">All Access</option>
          <option value="true">Open Access</option>
          <option value="false">Subscription</option>
        </select>
        <div className="result-count">{filtered.length} publication{filtered.length !== 1 ? 's' : ''}</div>
      </div>

      <div className="pubs-list">
        {filtered.length > 0
          ? filtered.map(p => <PublicationCard key={p.id} pub={p} />)
          : <EmptyState title="No publications found" desc="Try adjusting your filters." />
        }
      </div>
    </>
  );
}
